services:
  api:
    build: .
    ports:
      - '80:80'
    environment:
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
    volumes:
      - ./api:/app/api
    command: uvicorn api.main:app --host 0.0.0.0 --port 80 --reload

  redis:
    image: redis:alpine
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data

volumes:
  redis_data: # Define a volume for Redis data persistence
